### ISSUE TITLE
BBC: Bleadperl v5.41.3 breaks  NBI-Slurm-0.8.6 (due smartmatch removal)

### ISSUE THREAD

**Issue by andk** [quadram-institute-bioscience/NBI-Slurm#2]
Fail report: http://www.cpantesters.org/cpan/report/efcde0c8-6fe2-11ef-9abb-b122fe1fb034

**Comment by telatin** [comment]
I hopefully fixed this in 0.8.7 [tested on 5.41.4-threaded docker container]
